### PR TITLE
Move documentation to Sphinx

### PR DESCRIPTION
**Pull request by McSinyx**
Resolve GH-100, or at least create a concrete point for discussion.

@Mic92, may I have this repo's admin permission to config the web hooks (and other things in the future)?

### CODE REVIEW

**Comment by Mic92** [comment]
@McSinyx you are now organization owner.

**Comment by McSinyx** [comment]
Thanks, *organization owner*  sounds like something I should put in my biography :smile:

**Comment by McSinyx** [comment]
Woo-hoo it's finally working!

**Comment by mutlusun** [comment]
Thanks for your work!

**Comment by McSinyx** [comment]
@Mic92 and @mutlusun, may I have your thoughts on this?  The diff is huge so maybe taking a look at [the rendered docs](https://vicious--101.org.readthedocs.build/en/101/) might be faster.

**Comment by mutlusun** [comment]
Thanks for your work @McSinyx ! I will have a look at it this week ;)

**Comment by McSinyx** [comment]
Gentle ping!

**Comment by mutlusun** [comment]
Dear @McSinyx ,
I have now checked the generated doc files. Great work and LGTM! These docs are far easier to follow than the original readme.

I suggest that we shutdown the Github wiki now as it is not longer needed.

**Review by mutlusun — APPROVED** [review]

**Comment by McSinyx** [comment]
Thanks for the approval.  I'll go ahead and merge this now; anything to be found later on can be solved by follow-ups.

**Pull request merged**
